language: r
cache: packages

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

r_github_packages:
  - rstudio/shinyapps

branches:
  only:
    - master
    - dev

notifications:
  email:
    recipients:
    - rhafen@gmail.com
    on_success: change
    on_failure: change
