# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

# language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  # - which nvm || curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
  # - nvm install 0.10

install:
  - ./travis-tool.sh r_binary_install lattice base64enc knitr markdown shiny digest codetools hexbin ggplot2 jsonlite fastICA scagnostics
  - ./travis-tool.sh r_install rmongodb
  -
  - ./travis-tool.sh install_github tesseradata/datadr
  - # install protobuf
  - wget http://protobuf.googlecode.com/files/protobuf-2.4.1.tar.gz
  - tar -xzf protobuf-2.4.1.tar.gz
  - cd protobuf-2.4.1
  - ./configure # --prefix=...
  - make
  - make install
  - ./travis-tool.sh install_github tesseradata/RHIPE/code/R@v0.73
  -
  - ./travis-tool.sh install_deps
  # - npm install -g grunt-cli
  # - npm install ./

script:
  - ./travis-tool.sh run_tests
  - npm test

# after_failure:
#   - ./travis-tool.sh dump_logs
after_script:
  - ./travis-tool.sh dump_logs

language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g grunt-cli

branches:
  only:
    - master
    - dev
    - browser_test

notifications:
  email:
    on_success: change
    on_failure: change
