language: r

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

r_binary_packages:
  - lattice
  - base64enc
  - knitr
  - markdown
  - shiny
  - digest
  - codetools
  - hexbin
  - ggplot2
  - jsonlite
  - fastICA
  - scagnostics
  - magrittr
  - dplyr
  - testthat
  - roxygen2

r_github_packages:
  - hadley/httr
  - install_github
  - tesseradata/datadr
  - rstudio/shinyapps

branches:
  only:
    - master
    - dev

notifications:
  email:
    recipients:
    - rhafen@gmail.com
    on_success: change
    on_failure: change
